/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.examples.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Bicycle
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Bicycle extends Vehicle {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Bicycle() {
		super();
	}
	
}
