/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.examples.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Boat
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Boat extends Vehicle implements NeedALicense {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Boat() {
		super();
	}
	/**
	 * The documentation of the method canDrive.
	 * 
	 * @param driver
	 * @return
	 * 
	 * @generated
	 */
	public Boolean canDrive(Person driver) {
		// Start of user code for the body of canDrive
		// TODO should be implemented
		return null;
		// End of user code
	}
}
