/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.examples.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the interface NeedALicense.
 * 
 * @generated
 */
public interface NeedALicense {
	/**
	 * The documentation of the method canDrive.
	 * 
	 * @param driver
	 * @return
	 * 
	 * @generated
	 */
	public Boolean canDrive(Person driver);
	
}
