/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.examples.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Person
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Person {
	/**
	 * The documentation of the attribute name.
	 * 
	 * @generated
	 */
	private String name;
	
	/**
	 * The documentation of the attribute firstName.
	 * 
	 * @generated
	 */
	private String firstName;
	
	/**
	 * The documentation of the attribute dateOfBirth.
	 * 
	 * @generated
	 */
	private Date dateOfBirth;
	
	/**
	 * The documentation of the attribute emails.
	 * 
	 * @generated
	 */
	private List<String> emails;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Person() {
		super();
	}
	/**
	 * The documentation of the method getAge.
	 *  Calculate the age from the birthdate to now.
	 * @return
	 * 
	 * @generated
	 */
	public Integer getAge() {
		// Start of user code for the body of getAge
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	/**
	 * The documentation of the method getFullName.
	 * 
	 * @return
	 * 
	 * @generated
	 */
	public String getFullName() {
		// Start of user code for the body of getFullName
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	/**
	 * The documentation of the getter getName.
	 * 
	 * @generated
	 */
	public String getName() {
		return this.name;
	}
	
	/**
	 * The documentation of the setter setName.
	 * 
	 * @generated
	 */
	public void setName(String newName) {
		this.name = newName;
	}
	
	/**
	 * The documentation of the getter getFirstName.
	 * 
	 * @generated
	 */
	public String getFirstName() {
		return this.firstName;
	}
	
	/**
	 * The documentation of the setter setFirstName.
	 * 
	 * @generated
	 */
	public void setFirstName(String newFirstName) {
		this.firstName = newFirstName;
	}
	
	/**
	 * The documentation of the getter getDateOfBirth.
	 * 
	 * @generated
	 */
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}
	
	/**
	 * The documentation of the setter setDateOfBirth.
	 * 
	 * @generated
	 */
	public void setDateOfBirth(Date newDateOfBirth) {
		this.dateOfBirth = newDateOfBirth;
	}
	
	/**
	 * The documentation of the getter getEmails.
	 * 
	 * @generated
	 */
	public List<String> getEmails() {
		return this.emails;
	}
	
	/**
	 * The documentation of the setter setEmails.
	 * 
	 * @generated
	 */
	public void setEmails(List<String> newEmails) {
		this.emails = newEmails;
	}
}
