/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.examples.umltojava.model;

// Start of user code for imports
import java.util.*;
// End of user code

/**
 * The documentation of the class Vehicle
 * 
 * @author Acceleo 3 Example - UML to Java generator
 * @generated
 */
public class Vehicle {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Vehicle() {
		super();
	}
	/**
	 * The documentation of the method drive.
	 * 
	 * 
	 * @generated
	 */
	public void drive() {
		// Start of user code for the body of drive
		// TODO should be implemented
		// End of user code
	}
}
